/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AwardsCarousel: typeof import('./src/components/AwardsCarousel.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    ScrolledSection: typeof import('./src/components/ScrolledSection.vue')['default']
  }
}
